load(sound_data_dir('ph-iir/m-30-1_2-left.m7.mat'));

%process_entire_file_binaural_filter( ...
%process_stream_binaural_filter( ...
%    sound_data_dir('impulse-44-32-both.wav'), ...
%    mdl_tf, 44100, ...
%    sound_data_dir('ph-iir/m-30-1_2-both-fs.mlab-strm.wav'));

%process_entire_file_binaural_filter( ...
process_stream_binaural_filter( ...
     '/Users/mikhail/Sounds/PerfectSense_44_1.wav', ...
     mdl_tf, 44100, ...
     '/Users/mikhail/Sounds/PerfectSense_44_1-IIR.strm.wav');
